baseURL = 'https://mi-ki-ri.github.io/quote-block/'
languageCode = 'ja-jp'
title = 'QuoteBlock ~適当な引用~'
hasCJKLanguage = true

theme = "quoteblock"

[taxonomies]
    tag = "tags"
    category = "categories"
